# Values for blocks can be defined as follows:
# 
# By sound type:
# WOOD=1.0
# 
# By block tag:
# \#minecraft\:logs=1.0
# 
# By block ID:
# minecraft\:oak_log=1.0

# #aeronautics:envelope (Block Tag)
\#aeronautics\:envelope=0.1
# Amethyst (Sound Type)
AMETHYST=1.5
# Amethyst Cluster (Sound Type)
AMETHYST_CLUSTER=0.5
# Ancient Debris (Sound Type)
ANCIENT_DEBRIS=0.5
# Anvil (Sound Type)
ANVIL=0.5
# Azalea (Sound Type)
AZALEA=0.5
# Azalea Leaves (Sound Type)
AZALEA_LEAVES=0.5
# Bamboo (Sound Type)
BAMBOO=0.5
# Bamboo Sapling (Sound Type)
BAMBOO_SAPLING=0.5
# Bamboo Wood (Sound Type)
BAMBOO_WOOD=0.5
# Bamboo Wood Hanging Sign (Sound Type)
BAMBOO_WOOD_HANGING_SIGN=0.5
# Basalt (Sound Type)
BASALT=1.5
# Big Dripleaf (Sound Type)
BIG_DRIPLEAF=0.5
# Bone Block (Sound Type)
BONE_BLOCK=1.5
# Calcite (Sound Type)
CALCITE=1.5
# Candle (Sound Type)
CANDLE=0.5
# Cave Vines (Sound Type)
CAVE_VINES=0.5
# Chain (Sound Type)
CHAIN=0.5
# Cherry Leaves (Sound Type)
CHERRY_LEAVES=0.5
# Cherry Sapling (Sound Type)
CHERRY_SAPLING=0.5
# Cherry Wood (Sound Type)
CHERRY_WOOD=0.5
# Cherry Wood Hanging Sign (Sound Type)
CHERRY_WOOD_HANGING_SIGN=0.5
# Chiseled Bookshelf (Sound Type)
CHISELED_BOOKSHELF=0.5
# Copper (Sound Type)
COPPER=1.25
# Coral Block (Sound Type)
CORAL_BLOCK=0.2
# Crop (Sound Type)
CROP=0.5
# Decorated Pot (Sound Type)
DECORATED_POT=0.5
# Decorated Pot Cracked (Sound Type)
DECORATED_POT_CRACKED=0.5
# Deepslate (Sound Type)
DEEPSLATE=1.5
# Deepslate Bricks (Sound Type)
DEEPSLATE_BRICKS=1.5
# Deepslate Tiles (Sound Type)
DEEPSLATE_TILES=1.5
# Dripstone Block (Sound Type)
DRIPSTONE_BLOCK=0.5
# Flowering Azalea (Sound Type)
FLOWERING_AZALEA=0.5
# Froglight (Sound Type)
FROGLIGHT=0.5
# Frogspawn (Sound Type)
FROGSPAWN=0.5
# Fungus (Sound Type)
FUNGUS=0.5
# Gilded Blackstone (Sound Type)
GILDED_BLACKSTONE=0.5
# Glass (Sound Type)
GLASS=0.75
# Glow Lichen (Sound Type)
GLOW_LICHEN=0.5
# Grass (Sound Type)
GRASS=0.3
# Gravel (Sound Type)
GRAVEL=0.3
# Hanging Roots (Sound Type)
HANGING_ROOTS=0.5
# Hanging Sign (Sound Type)
HANGING_SIGN=0.5
# Hard Crop (Sound Type)
HARD_CROP=0.5
# Honey Block (Sound Type)
HONEY_BLOCK=0.1
# Ladder (Sound Type)
LADDER=0.5
# Lantern (Sound Type)
LANTERN=0.5
# Large Amethyst Bud (Sound Type)
LARGE_AMETHYST_BUD=0.5
# Lily Pad (Sound Type)
LILY_PAD=0.5
# Lodestone (Sound Type)
LODESTONE=0.5
# Mangrove Roots (Sound Type)
MANGROVE_ROOTS=0.5
# Medium Amethyst Bud (Sound Type)
MEDIUM_AMETHYST_BUD=0.5
# Metal (Sound Type)
METAL=1.25
# Moss (Sound Type)
MOSS=0.1
# Moss Carpet (Sound Type)
MOSS_CARPET=0.5
# Mud (Sound Type)
MUD=0.5
# Muddy Mangrove Roots (Sound Type)
MUDDY_MANGROVE_ROOTS=0.5
# Mud Bricks (Sound Type)
MUD_BRICKS=0.5
# Netherite Block (Sound Type)
NETHERITE_BLOCK=1.5
# Netherrack (Sound Type)
NETHERRACK=1.1
# Nether Bricks (Sound Type)
NETHER_BRICKS=1.5
# Nether Gold Ore (Sound Type)
NETHER_GOLD_ORE=1.1
# Nether Ore (Sound Type)
NETHER_ORE=1.1
# Nether Sprouts (Sound Type)
NETHER_SPROUTS=0.5
# Nether Wart (Sound Type)
NETHER_WART=0.5
# Nether Wood (Sound Type)
NETHER_WOOD=0.5
# Nether Wood Hanging Sign (Sound Type)
NETHER_WOOD_HANGING_SIGN=0.5
# Nylium (Sound Type)
NYLIUM=0.5
# Packed Mud (Sound Type)
PACKED_MUD=0.5
# Pointed Dripstone (Sound Type)
POINTED_DRIPSTONE=0.5
# Polished Deepslate (Sound Type)
POLISHED_DEEPSLATE=1.5
# Powder Snow (Sound Type)
POWDER_SNOW=0.5
# Rooted Dirt (Sound Type)
ROOTED_DIRT=0.5
# Roots (Sound Type)
ROOTS=0.5
# Sand (Sound Type)
SAND=0.2
# Scaffolding (Sound Type)
SCAFFOLDING=0.5
# Sculk (Sound Type)
SCULK=0.5
# Sculk Catalyst (Sound Type)
SCULK_CATALYST=0.5
# Sculk Sensor (Sound Type)
SCULK_SENSOR=0.5
# Sculk Shrieker (Sound Type)
SCULK_SHRIEKER=0.5
# Sculk Vein (Sound Type)
SCULK_VEIN=0.5
# Shroomlight (Sound Type)
SHROOMLIGHT=0.5
# Slime Block (Sound Type)
SLIME_BLOCK=0.5
# Small Amethyst Bud (Sound Type)
SMALL_AMETHYST_BUD=0.5
# Small Dripleaf (Sound Type)
SMALL_DRIPLEAF=0.5
# Snow (Sound Type)
SNOW=0.15
# Soul Sand (Sound Type)
SOUL_SAND=0.2
# Soul Soil (Sound Type)
SOUL_SOIL=0.2
# Spore Blossom (Sound Type)
SPORE_BLOSSOM=0.5
# Stem (Sound Type)
STEM=0.4
# Stone (Sound Type)
STONE=1.5
# Suspicious Gravel (Sound Type)
SUSPICIOUS_GRAVEL=0.5
# Suspicious Sand (Sound Type)
SUSPICIOUS_SAND=0.5
# Sweet Berry Bush (Sound Type)
SWEET_BERRY_BUSH=0.5
# Tuff (Sound Type)
TUFF=1.5
# Twisting Vines (Sound Type)
TWISTING_VINES=0.5
# Vine (Sound Type)
VINE=0.5
# Wart Block (Sound Type)
WART_BLOCK=0.5
# Weeping Vines (Sound Type)
WEEPING_VINES=0.5
# Wet Grass (Sound Type)
WET_GRASS=0.5
# Wood (Sound Type)
WOOD=0.4
# Wool (Sound Type)
WOOL=0.1
# block.aeronautics.adjustable_burner (Block)
aeronautics\:adjustable_burner=1.5
# block.aeronautics.andesite_propeller (Block)
aeronautics\:andesite_propeller=0.4
# block.aeronautics.gyroscopic_propeller_bearing (Block)
aeronautics\:gyroscopic_propeller_bearing=1.25
# block.aeronautics.levitite (Block)
aeronautics\:levitite=1.5
# block.aeronautics.mounted_potato_cannon (Block)
aeronautics\:mounted_potato_cannon=1.25
# block.aeronautics.pearlescent_levitite (Block)
aeronautics\:pearlescent_levitite=1.5
# block.aeronautics.propeller_bearing (Block)
aeronautics\:propeller_bearing=1.25
# block.aeronautics.smart_propeller (Block)
aeronautics\:smart_propeller=1.25
# block.aeronautics.steam_vent (Block)
aeronautics\:steam_vent=1.5
# block.aeronautics.white_envelope (Block)
aeronautics\:white_envelope=0.1
# block.aeronautics.white_envelope_encased_shaft (Block)
aeronautics\:white_envelope_encased_shaft=0.2
# block.aeronautics.wooden_propeller (Block)
aeronautics\:wooden_propeller=0.4
# block.cataclysm.altar_of_abyss (Block)
cataclysm\:altar_of_abyss=1.2
# block.cataclysm.altar_of_fire (Block)
cataclysm\:altar_of_fire=1.2
# block.cataclysm.altar_of_void (Block)
cataclysm\:altar_of_void=1.2
# block.cataclysm.ancient_metal_block (Block)
cataclysm\:ancient_metal_block=1.5
# block.cataclysm.chorus_planks (Block)
cataclysm\:chorus_planks=0.35
# block.cataclysm.chorus_stem (Block)
cataclysm\:chorus_stem=0.35
# block.cataclysm.cursium_block (Block)
cataclysm\:cursium_block=1.5
# block.cataclysm.door_of_seal (Block)
cataclysm\:door_of_seal=1.2
# block.cataclysm.ignitium_block (Block)
cataclysm\:ignitium_block=1.5
# block.cataclysm.obsidian_bricks (Block)
cataclysm\:obsidian_bricks=1.55
# block.cataclysm.polished_end_stone (Block)
cataclysm\:polished_end_stone=1.35
# block.cataclysm.void_stone (Block)
cataclysm\:void_stone=1.35
# block.cataclysm.witherite_block (Block)
cataclysm\:witherite_block=1.5
# block.create.andesite_casing (Block)
create\:andesite_casing=1.0
# block.create.andesite_encased_cogwheel (Block)
create\:andesite_encased_cogwheel=1.1
# block.create.andesite_encased_shaft (Block)
create\:andesite_encased_shaft=1.1
# block.create.blaze_burner (Block)
create\:blaze_burner=1.25
# block.create.brass_casing (Block)
create\:brass_casing=1.25
# block.create.brass_encased_cogwheel (Block)
create\:brass_encased_cogwheel=1.25
# block.create.brass_encased_shaft (Block)
create\:brass_encased_shaft=1.25
# block.create.cardboard_block (Block)
create\:cardboard_block=0.15
# block.create.chute (Block)
create\:chute=1.35
# block.create.clockwork_bearing (Block)
create\:clockwork_bearing=1.15
# block.create.clutch (Block)
create\:clutch=1.1
# block.create.cogwheel (Block)
create\:cogwheel=0.4
# block.create.copper_casing (Block)
create\:copper_casing=1.25
# block.create.deployer (Block)
create\:deployer=1.0
# block.create.depot (Block)
create\:depot=1.1
# block.create.elevator_pulley (Block)
create\:elevator_pulley=1.0
# block.create.encased_chain_drive (Block)
create\:encased_chain_drive=1.15
# block.create.encased_fan (Block)
create\:encased_fan=1.25
# block.create.encased_fluid_pipe (Block)
create\:encased_fluid_pipe=1.25
# block.create.fluid_pipe (Block)
create\:fluid_pipe=1.25
# block.create.fluid_tank (Block)
create\:fluid_tank=1.0
# block.create.gearbox (Block)
create\:gearbox=1.1
# block.create.gearshift (Block)
create\:gearshift=1.1
# block.create.glass_fluid_pipe (Block)
create\:glass_fluid_pipe=0.9
# block.create.industrial_iron_block (Block)
create\:industrial_iron_block=1.25
# block.create.large_cogwheel (Block)
create\:large_cogwheel=0.4
# block.create.linear_chassis (Block)
create\:linear_chassis=0.4
# block.create.lit_blaze_burner (Block)
create\:lit_blaze_burner=1.25
# block.create.mechanical_bearing (Block)
create\:mechanical_bearing=1.15
# block.create.mechanical_drill (Block)
create\:mechanical_drill=1.35
# block.create.mechanical_harvester (Block)
create\:mechanical_harvester=1.25
# block.create.mechanical_plough (Block)
create\:mechanical_plough=1.25
# block.create.mechanical_pump (Block)
create\:mechanical_pump=1.25
# block.create.mechanical_roller (Block)
create\:mechanical_roller=1.25
# block.create.mechanical_saw (Block)
create\:mechanical_saw=1.35
# block.create.nozzle (Block)
create\:nozzle=0.7
# block.create.radial_chassis (Block)
create\:radial_chassis=0.4
# block.create.rope_pulley (Block)
create\:rope_pulley=0.7
# block.create.sail_frame (Block)
create\:sail_frame=0.35
# block.create.shaft (Block)
create\:shaft=1.25
# block.create.smart_chute (Block)
create\:smart_chute=1.35
# block.create.smart_fluid_pipe (Block)
create\:smart_fluid_pipe=1.25
# block.create.speedometer (Block)
create\:speedometer=0.5
# block.create.steam_engine (Block)
create\:steam_engine=1.25
# block.create.sticker (Block)
create\:sticker=0.4
# block.create.stressometer (Block)
create\:stressometer=0.5
# block.create.weighted_ejector (Block)
create\:weighted_ejector=1.1
# block.create.white_sail (Block)
create\:white_sail=0.2
# block.create.windmill_bearing (Block)
create\:windmill_bearing=1.15
# block.create_connected.crank_wheel (Block)
create_connected\:crank_wheel=1.15
# block.create_connected.fluid_vessel (Block)
create_connected\:fluid_vessel=1.15
# block.create_connected.inventory_access_port (Block)
create_connected\:inventory_access_port=1.15
# block.create_connected.kinetic_bridge (Block)
create_connected\:kinetic_bridge=1.15
# block.create_connected.sequenced_pulse_generator (Block)
create_connected\:sequenced_pulse_generator=1.15
# block.create_connected.shear_pin (Block)
create_connected\:shear_pin=1.15
# block.farmersdelight.acacia_cabinet (Block)
farmersdelight\:acacia_cabinet=0.4
# block.farmersdelight.bamboo_basket (Block)
farmersdelight\:bamboo_basket=0.2
# block.farmersdelight.bamboo_cabinet (Block)
farmersdelight\:bamboo_cabinet=0.4
# block.farmersdelight.birch_cabinet (Block)
farmersdelight\:birch_cabinet=0.4
# block.farmersdelight.canvas_rug (Block)
farmersdelight\:canvas_rug=0.05
# block.farmersdelight.cherry_cabinet (Block)
farmersdelight\:cherry_cabinet=0.4
# block.farmersdelight.cooking_pot (Block)
farmersdelight\:cooking_pot=1.2
# block.farmersdelight.crimson_cabinet (Block)
farmersdelight\:crimson_cabinet=0.4
# block.farmersdelight.cutting_board (Block)
farmersdelight\:cutting_board=0.4
# block.farmersdelight.dark_oak_cabinet (Block)
farmersdelight\:dark_oak_cabinet=0.4
# block.farmersdelight.jungle_cabinet (Block)
farmersdelight\:jungle_cabinet=0.4
# block.farmersdelight.mangrove_cabinet (Block)
farmersdelight\:mangrove_cabinet=0.4
# block.farmersdelight.oak_cabinet (Block)
farmersdelight\:oak_cabinet=0.4
# block.farmersdelight.organic_compost (Block)
farmersdelight\:organic_compost=0.14
# block.farmersdelight.rich_soil (Block)
farmersdelight\:rich_soil=0.14
# block.farmersdelight.rope (Block)
farmersdelight\:rope=0.2
# block.farmersdelight.skillet (Block)
farmersdelight\:skillet=1.2
# block.farmersdelight.spruce_cabinet (Block)
farmersdelight\:spruce_cabinet=0.4
# block.farmersdelight.stove (Block)
farmersdelight\:stove=1.2
# block.farmersdelight.straw_bale (Block)
farmersdelight\:straw_bale=0.08
# block.farmersdelight.warped_cabinet (Block)
farmersdelight\:warped_cabinet=0.4
# Air (Block)
minecraft\:air=1.25
# block.offroad.borehead_bearing (Block)
offroad\:borehead_bearing=1.5
# block.offroad.rockcutting_wheel (Block)
offroad\:rockcutting_wheel=1.5
# block.offroad.wheel_mount (Block)
offroad\:wheel_mount=1.1
# block.quark.encased_pipe (Block)
quark\:encased_pipe=1.1
# block.quark.ender_watcher (Block)
quark\:ender_watcher=1.15
# block.quark.grate (Block)
quark\:grate=1.2
# block.quark.magnetized_block (Block)
quark\:magnetized_block=1.15
# block.quark.monster_box (Block)
quark\:monster_box=1.15
# block.quark.paper_lantern (Block)
quark\:paper_lantern=0.06
# block.quark.paper_wall (Block)
quark\:paper_wall=0.06
# block.quark.pipe (Block)
quark\:pipe=1.1
# block.quark.potato_crate (Block)
quark\:potato_crate=0.18
# block.railways.buffer (Block)
railways\:buffer=1.2
# block.railways.fuel_tank (Block)
railways\:fuel_tank=1.35
# block.railways.locometal_boiler (Block)
railways\:locometal_boiler=1.35
# block.railways.locometal_pillar (Block)
railways\:locometal_pillar=1.45
# block.railways.portable_fuel_interface (Block)
railways\:portable_fuel_interface=1.15
# block.railways.semaphore (Block)
railways\:semaphore=1.2
# block.railways.track_coupler (Block)
railways\:track_coupler=1.2
# block.simulated.altitude_sensor (Block)
simulated\:altitude_sensor=0.5
# block.simulated.auger_cog (Block)
simulated\:auger_cog=1.5
# block.simulated.auger_shaft (Block)
simulated\:auger_shaft=1.5
# block.simulated.directional_gearshift (Block)
simulated\:directional_gearshift=1.1
# block.simulated.gimbal_sensor (Block)
simulated\:gimbal_sensor=1.25
# block.simulated.laser_pointer (Block)
simulated\:laser_pointer=1.25
# block.simulated.laser_sensor (Block)
simulated\:laser_sensor=0.7
# block.simulated.merging_glue (Block)
simulated\:merging_glue=0.15
# block.simulated.navigation_table (Block)
simulated\:navigation_table=0.4
# block.simulated.physics_assembler (Block)
simulated\:physics_assembler=0.6
# block.simulated.red_portable_engine (Block)
simulated\:red_portable_engine=1.4
# block.simulated.rope_connector (Block)
simulated\:rope_connector=1.1
# block.simulated.rope_winch (Block)
simulated\:rope_winch=1.1
# block.simulated.swivel_bearing (Block)
simulated\:swivel_bearing=1.5
# block.simulated.swivel_bearing_link_block (Block)
simulated\:swivel_bearing_link_block=1.5
# block.simulated.torsion_spring (Block)
simulated\:torsion_spring=1.25
# block.simulated.velocity_sensor (Block)
simulated\:velocity_sensor=0.5
# block.supplementaries.awning (Block)
supplementaries\:awning=0.06
# block.supplementaries.awning_black (Block)
supplementaries\:awning_black=0.06
# block.supplementaries.awning_blue (Block)
supplementaries\:awning_blue=0.06
# block.supplementaries.awning_brown (Block)
supplementaries\:awning_brown=0.06
# block.supplementaries.awning_cyan (Block)
supplementaries\:awning_cyan=0.06
# block.supplementaries.awning_gray (Block)
supplementaries\:awning_gray=0.06
# block.supplementaries.awning_green (Block)
supplementaries\:awning_green=0.06
# block.supplementaries.awning_light_blue (Block)
supplementaries\:awning_light_blue=0.06
# block.supplementaries.awning_light_gray (Block)
supplementaries\:awning_light_gray=0.06
# block.supplementaries.awning_lime (Block)
supplementaries\:awning_lime=0.06
# block.supplementaries.awning_magenta (Block)
supplementaries\:awning_magenta=0.06
# block.supplementaries.awning_orange (Block)
supplementaries\:awning_orange=0.06
# block.supplementaries.awning_pink (Block)
supplementaries\:awning_pink=0.06
# block.supplementaries.awning_purple (Block)
supplementaries\:awning_purple=0.06
# block.supplementaries.awning_red (Block)
supplementaries\:awning_red=0.06
# block.supplementaries.awning_white (Block)
supplementaries\:awning_white=0.06
# block.supplementaries.awning_yellow (Block)
supplementaries\:awning_yellow=0.06
# block.supplementaries.bellows (Block)
supplementaries\:bellows=0.3
# block.supplementaries.blackboard (Block)
supplementaries\:blackboard=0.45
# block.supplementaries.bubble_block (Block)
supplementaries\:bubble_block=0.06
# block.supplementaries.cannon (Block)
supplementaries\:cannon=1.35
# block.supplementaries.cannonball (Block)
supplementaries\:cannonball=1.35
# block.supplementaries.clock_block (Block)
supplementaries\:clock_block=0.95
# block.supplementaries.crank (Block)
supplementaries\:crank=0.95
# block.supplementaries.faucet (Block)
supplementaries\:faucet=0.95
# block.supplementaries.globe (Block)
supplementaries\:globe=0.95
# block.supplementaries.jar (Block)
supplementaries\:jar=0.75
# block.supplementaries.present (Block)
supplementaries\:present=0.08
# block.supplementaries.pulley_block (Block)
supplementaries\:pulley_block=0.12
# block.supplementaries.rope (Block)
supplementaries\:rope=0.12
# block.supplementaries.rope_knot (Block)
supplementaries\:rope_knot=0.12
# block.supplementaries.sack (Block)
supplementaries\:sack=0.08
# block.supplementaries.sconce (Block)
supplementaries\:sconce=0.95
# block.supplementaries.slidy_block (Block)
supplementaries\:slidy_block=0.18
# block.supplementaries.spring_launcher (Block)
supplementaries\:spring_launcher=1.35
