name = "Allium Season 13"
author = "Allium"
version = "1.0.0"
description = "Allium Season 13 - Minecraft 1.21.1 NeoForge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61063d5fea2c665e9c154e76384ead9dbbec1495ed12467df8d44f7179c24ec4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
