name = "Allium Season 13"
author = "Allium"
version = "1.0.0"
description = "Allium Season 13 - Minecraft 1.21.1 NeoForge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "942d5c57cfa8977520791626e974331d649d2263a4fd85693f652259a16070da"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
