name = "Allium Season 13"
author = "Allium"
version = "1.0.0"
description = "Allium Season 13 - Minecraft 1.21.1 NeoForge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98222eb4983431e037cc9aadb8e761a9c0971ff29a945fe83d173fdd63ed13a9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
